const DEFAULT_BLOCKS = {
  "controls_if_else": `<xml><block type="controls_if"><mutation else="1"></mutation></block></xml>`,
  "controls_if_else_if_else": `<xml><block type="controls_if"><mutation elseif="1" else="1"></mutation></block></xml>`,
  "logic_compare_notEqualTo": `<xml><block type="logic_compare"><field name="OP">NEQ</field></block></xml>`,
  "logic_or": `<xml><block type = "logic_operation"><mutation items="2"></mutation><field name="OP">OR</field></block></xml>`,
  "text_join": `<xml><block type = "text_join"><mutation items="2"></mutation></block></xml>`,
  "text_compare_gt": `<xml><block type="text_compare"><field name="OP">GT</field></block></xml>`,
  "text_compare_eq": `<xml><block type="text_compare"><field name="OP">EQUAL</field></block></xml>`,
  "text_compare_neq": `<xml><block type="text_compare"><field name="OP">NEQ</field></block></xml>`,
  "text_downCase": `<xml><block type="text_changeCase"><field name="OP">DOWNCASE</field></block></xml>`,
  "text_containsAny": `<xml><block type="text_contains"><mutation mode="CONTAINS_ANY"></mutation><field name="OP">CONTAINS_ANY</field></block></xml>`,
  "text_containsAll": `<xml><block type="text_contains"><mutation mode="CONTAINS_ALL"></mutation><field name="OP">CONTAINS_ALL</field></block></xml>`,
  "text_splitAtFirst": `<xml><block type="text_split"><mutation mode="SPLITATFIRST"></mutation><field name="OP">SPLITATFIRST</field></block></xml>`,
  "text_splitAtFirstOfAny": `<xml><block type="text_split"><mutation mode="SPLITATFIRSTOFANY"></mutation><field name="OP">SPLITATFIRSTOFANY</field></block></xml>`,
  "text_splitAtAny": `<xml><block type="text_split"><mutation mode="SPLITATANY"></mutation><field name="OP">SPLITATANY</field></block></xml>`,
  "text_replace_mappings_dictionary_order": `<xml><block type="text_replace_mappings"><field name="OP">DICTIONARY_ORDER</field></block></xml>`,
  "lists_create_empty": `<xml><block type="lists_create_with"><mutation items="0"></mutation></block></xml>`,
  "lists_lookup_in_pairs": `<xml><block type="lists_lookup_in_pairs"><value name="NOTFOUND"><block type="text"><field name="TEXT">not found</field></block></value></block></xml>`,
  "lists_join_with_separator": `<xml><block type="lists_join_with_separator"><value name="SEPARATOR"><block type="text"><field name="TEXT"></field></block></value></block></xml>`,
  "lexical_variable_get": `<xml><block type="lexical_variable_get"><field name="VAR">global name</field></block></xml>`,
  "lexical_variable_set": `<xml><block type="lexical_variable_set"><field name="VAR">global name</field></block></xml>`,
  "color_make_color": `<xml ><block type=\"color_make_color\"  x=\"-733\" y=\"114\"><value name=\"COLORLIST\"><block type=\"lists_create_with\"  inline=\"false\"><mutation items=\"3\"></mutation><value name=\"ADD0\"><block type=\"math_number\" ><field name=\"NUM\">255</field></block></value><value name=\"ADD1\"><block type=\"math_number\" ><field name=\"NUM\">0</field></block></value><value name=\"ADD2\"><block type=\"math_number\" ><field name=\"NUM\">0</field></block></value></block></value></block></xml>`,
  "color_make_color_with_alpha": `<xml ><block type=\"color_make_color\"  x=\"-733\" y=\"114\"><value name=\"COLORLIST\"><block type=\"lists_create_with\"  inline=\"false\"><mutation items=\"4\"></mutation><value name=\"ADD0\"><block type=\"math_number\" ><field name=\"NUM\">255</field></block></value><value name=\"ADD1\"><block type=\"math_number\" ><field name=\"NUM\">0</field></block></value><value name=\"ADD2\"><block type=\"math_number\" ><field name=\"NUM\">0</field></block></value><value name=\"ADD3\"><block type=\"math_number\" ><field name=\"NUM\">0</field></block></value></block></value></block></xml>`,
  "dict_ex_1": "<xml ><block type=\"dictionaries_create_with\"  x=\"-731\" y=\"70\"><mutation items=\"5\"></mutation><value name=\"ADD0\"><block type=\"pair\" ><value name=\"KEY\"><block type=\"text\" ><field name=\"TEXT\">id</field></block></value><value name=\"VALUE\"><block type=\"math_number\" ><field name=\"NUM\">1</field></block></value></block></value><value name=\"ADD1\"><block type=\"pair\" ><value name=\"KEY\"><block type=\"text\" ><field name=\"TEXT\">name</field></block></value><value name=\"VALUE\"><block type=\"text\" ><field name=\"TEXT\">Tim the Beaver</field></block></value></block></value><value name=\"ADD2\"><block type=\"pair\" ><value name=\"KEY\"><block type=\"text\" ><field name=\"TEXT\">school</field></block></value><value name=\"VALUE\"><block type=\"dictionaries_create_with\" ><mutation items=\"1\"></mutation><value name=\"ADD0\"><block type=\"pair\" ><value name=\"KEY\"><block type=\"text\" ><field name=\"TEXT\">name</field></block></value><value name=\"VALUE\"><block type=\"text\" ><field name=\"TEXT\">Massachusetts Institute of Technology</field></block></value></block></value></block></value></block></value><value name=\"ADD3\"><block type=\"pair\" ><value name=\"KEY\"><block type=\"text\" ><field name=\"TEXT\">enrolled</field></block></value><value name=\"VALUE\"><block type=\"logic_boolean\" ><field name=\"BOOL\">TRUE</field></block></value></block></value><value name=\"ADD4\"><block type=\"pair\" ><value name=\"KEY\"><block type=\"text\" ><field name=\"TEXT\">classes</field></block></value><value name=\"VALUE\"><block type=\"lists_create_with\" ><mutation items=\"3\"></mutation><value name=\"ADD0\"><block type=\"text\" ><field name=\"TEXT\">6.001</field></block></value><value name=\"ADD1\"><block type=\"text\" ><field name=\"TEXT\">18.01</field></block></value><value name=\"ADD2\"><block type=\"text\" ><field name=\"TEXT\">8.01</field></block></value></block></value></block></value></block></xml>",
  "dictionaries_create_with_empty": "<xml ><block type=\"dictionaries_create_with\"  x=\"-639\" y=\"105\"><mutation items=\"0\"></mutation></block></xml>",
  "dictionaries_create_with": "<xml ><block type=\"dictionaries_create_with\"  x=\"-727\" y=\"55\"><mutation items=\"2\"></mutation><value name=\"ADD0\"><block type=\"pair\" ></block></value><value name=\"ADD1\"><block type=\"pair\" ></block></value></block></xml>",
  "dictionaries_get_value_for_key": "<xml ><block type=\"dictionaries_lookup\"  x=\"-572\" y=\"-107\"><value name=\"NOTFOUND\"><block type=\"text\" ><field name=\"TEXT\">not found</field></block></value></block></xml>",
  "dictionaries_recursive_lookup": "<xml ><block type=\"dictionaries_recursive_lookup\"  x=\"-147\" y=\"-50\"><value name=\"NOTFOUND\"><block type=\"text\" ><field name=\"TEXT\">not found</field></block></value></block></xml>",
  "dict_ex_2": "<xml><block  type=\"logic_compare\"  inline=\"false\"><field name=\"OP\">EQ</field><value name=\"A\"><block type=\"dictionaries_dict_to_alist\" ><value name=\"DICT\"><block type=\"dictionaries_alist_to_dict\" ><value name=\"PAIRS\"><block type=\"lists_create_with\" ><mutation items=\"2\"></mutation><value name=\"ADD0\"><block type=\"lists_create_with\" ><mutation items=\"2\"></mutation><value name=\"ADD0\"><block type=\"text\" ><field name=\"TEXT\">key1</field></block></value><value name=\"ADD1\"><block type=\"text\" ><field name=\"TEXT\">value1</field></block></value></block></value><value name=\"ADD1\"><block type=\"lists_create_with\" ><mutation items=\"2\"></mutation><value name=\"ADD0\"><block type=\"text\" ><field name=\"TEXT\">key2</field></block></value><value name=\"ADD1\"><block type=\"text\" ><field name=\"TEXT\">value2</field></block></value></block></value></block></value></block></value></block></value><value name=\"B\"><block type=\"lists_create_with\" ><mutation items=\"2\"></mutation><value name=\"ADD0\"><block type=\"lists_create_with\" ><mutation items=\"2\"></mutation><value name=\"ADD0\"><block type=\"text\" ><field name=\"TEXT\">key1</field></block></value><value name=\"ADD1\"><block type=\"text\" ><field name=\"TEXT\">value1</field></block></value></block></value><value name=\"ADD1\"><block type=\"lists_create_with\" ><mutation items=\"2\"></mutation><value name=\"ADD0\"><block type=\"text\" ><field name=\"TEXT\">key2</field></block></value><value name=\"ADD1\"><block type=\"text\" ><field name=\"TEXT\">value2</field></block></value></block></value></block></value></block></xml>",
  "math_number_radix_bin": "<xml><block  type=\"math_number_radix\" ><field name=\"OP\">BIN</field><field name=\"NUM\">0</field></block></xml>",
  "math_number_radix_oct": "<xml><block  type=\"math_number_radix\" ><field name=\"OP\">OCT</field><field name=\"NUM\">0</field></block></xml>",
  "math_number_radix_hax": "<xml><block  type=\"math_number_radix\" ><field name=\"OP\">HEX</field><field name=\"NUM\">0</field></block></xml>",
  "math_compare_neq": "<xml><block  type=\"math_compare\" ><field name=\"OP\">NEQ</field></block></xml>",
  "math_compare_gt": "<xml><block  type=\"math_compare\" ><field name=\"OP\">GT</field></block></xml>",
  "math_compare_gt_eq": "<xml><block  type=\"math_compare\" ><field name=\"OP\">GTE</field></block></xml>",
  "math_compare_lt": "<xml><block  type=\"math_compare\" ><field name=\"OP\">LT</field></block></xml>",
  "math_compare_lt_eq": "<xml><block type=\"math_compare\"><field name=\"OP\">LTE</field></block></xml>",
  "math_on_list_max": "<xml><block type=\"math_on_list\" ><mutation items=\"2\"></mutation><field name=\"OP\">MAX</field></block></xml>",
  "math_single_abs": "<xml><block type=\"math_single\"><field name=\"OP\">ABS</field></block></xml>",
  "math_single_neg": "<xml><block type=\"math_single\"><field name=\"OP\">NEG</field></block></xml>",
  "math_single_log": "<xml><block type=\"math_single\"><field name=\"OP\">LN</field></block></xml>",
  "math_single_exp": "<xml><block type=\"math_single\"><field name=\"OP\">EXP</field></block></xml>",
  "math_single_round": "<xml><block type=\"math_single\"><field name=\"OP\">ROUND</field></block></xml>",
  "math_single_cei": "<xml><block type=\"math_single\"><field name=\"OP\">CEILING</field></block></xml>",
  "math_single_floor": "<xml><block type=\"math_single\"><field name=\"OP\">FLOOR</field></block></xml>",
  "math_divide_rem": "<xml><block type=\"math_divide\" ><field name=\"OP\">REMAINDER</field></block></xml>",
  "math_divide_que": "<xml><block type=\"math_divide\" ><field name=\"OP\">QUOTIENT</field></block></xml>",
  "math_trig_arc_sin": '<xml><block type="math_tan"><field name="OP">ASIN</field></block></xml>',
  "math_trig_arc_cos": '<xml><block type="math_tan"><field name="OP">ACOS</field></block></xml>',
  "math_trig_arc_tan": '<xml><block type="math_tan"><field name="OP">ATAN</field></block></xml>',
  "math_convert_angles_d_r": '<xml>  <block type="math_convert_angles" ><field name="OP">DEGREES_TO_RADIANS</field></block></xml>',
  "math_is_num_1": '<xml><block type="math_is_a_number" ><field name="OP">BASE10</field></block></xml>',
  "math_is_num_2": '<xml><block type="math_is_a_number" ><field name="OP">HEXADECIMAL</field></block></xml>',
  "math_is_num_3": '<xml>  <block type="math_is_a_number" ><field name="OP">BINARY</field></block></xml>',
  "math_con_num_1": '<xml><block type="math_convert_number" ><field name="OP">HEX_TO_DEC</field></block></xml>',
  "math_con_num_2": '<xml><block type="math_convert_number" ><field name="OP">BIN_TO_DEC</field></block></xml>',
  "math_con_num_3": '<xml><block type="math_convert_number" ><field name="OP">DEC_TO_BIN</field></block></xml>',
  "math_bitwise_or": '<xml><block  type=\"math_bitwise\" ><mutation items=\"2\"></mutation><field name=\"OP\">BITIOR</field></block></xml>',
  "math_bitwise_exor": '<xml><block  type=\"math_bitwise\" ><mutation items=\"2\"></mutation><field name=\"OP\">BITXOR</field></block></xml>',
}